### ISSUE TITLE
С чего начнем востановление?

### ISSUE THREAD

**Issue by konstantin24121** [KinoFind/kinopoi.sk#1]
Язык? 
Framework?
Будут ли оригиналы базы данных?

**Comment by mrslain** [comment]
Сейчас все это активно обсуждается в ВК.
Решаем на чем будем писать.
Я тяну в сторону ruby.
Но из рубистов я только один.

**Comment by mrslain** [comment]
Если писать на php будет много проблем с выбором Framework`a.
Да и разработка затянется на не определенный срок.
